import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#8B5CF6',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 90,
    alignItems: 'center',
  },
  mainCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 32,
    padding: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.88)',
    shadowColor: '#4C1D95',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 8,
  },
  header: {
    alignItems: 'center',
    marginBottom: 16,
  },
  badge: {
    backgroundColor: 'rgba(109, 40, 217, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(109, 40, 217, 0.25)',
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 20,
    marginBottom: 8,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#6D28D9',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  title: {
    fontSize: 22,
    fontWeight: '900',
    color: '#2E1065',
    marginBottom: 4,
    letterSpacing: -0.3,
  },
  subtitle: {
    fontSize: 12.5,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 17,
  },
  alertBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(254, 243, 199, 0.85)',
    borderRadius: 22,
    padding: 14,
    borderWidth: 1.5,
    borderColor: 'rgba(253, 230, 138, 0.95)',
    gap: 12,
    marginBottom: 20,
    shadowColor: '#B45309',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
  },
  alertBannerIcon: {
    fontSize: 24,
  },
  alertBannerContent: {
    flex: 1,
  },
  alertBannerTitle: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#92400E',
    marginBottom: 2,
  },
  alertBannerDesc: {
    fontSize: 11.5,
    color: '#B45309',
    lineHeight: 16,
  },
  sectionHeader: {
    fontSize: 13,
    fontWeight: '800',
    color: '#6D28D9',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 12,
    marginTop: 4,
  },
  activityWindowCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.78)',
    borderRadius: 22,
    padding: 14,
    borderWidth: 1.2,
    borderColor: 'rgba(255, 255, 255, 0.9)',
    marginBottom: 10,
    shadowColor: '#4C1D95',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  actTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  actNameGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  actIcon: {
    fontSize: 22,
  },
  actName: {
    fontSize: 14,
    fontWeight: '800',
    color: '#2E1065',
  },
  actCategory: {
    fontSize: 11,
    color: '#6B7280',
  },
  conditionTag: {
    backgroundColor: '#D1FAE5',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#A7F3D0',
  },
  conditionTagText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#065F46',
  },
  slotRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: 'rgba(255, 255, 255, 0.65)',
    borderRadius: 14,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: '#EDE9FE',
  },
  slotItem: {
    alignItems: 'center',
  },
  slotLabel: {
    fontSize: 10,
    color: '#6B7280',
    marginBottom: 2,
    fontWeight: '600',
  },
  slotTime: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1F2937',
  },
  slotMetric: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6D28D9',
  },
  slotDivider: {
    width: 1,
    height: 20,
    backgroundColor: '#E5E7EB',
  },
  gaugesRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  gaugeBox: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.78)',
    borderRadius: 18,
    padding: 10,
    alignItems: 'center',
    borderWidth: 1.2,
    borderColor: 'rgba(255, 255, 255, 0.9)',
    shadowColor: '#4C1D95',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
  },
  gaugeIcon: {
    fontSize: 18,
    marginBottom: 4,
  },
  gaugeVal: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#2E1065',
    textAlign: 'center',
  },
  gaugeSub: {
    fontSize: 9.5,
    color: '#6B7280',
    marginTop: 2,
    textAlign: 'center',
    fontWeight: '500',
  },
  bottomSpacer: {
    height: 40,
  },
})
