import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#8B5CF6',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 90,
    alignItems: 'center',
  },
  mainCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 32,
    paddingVertical: 24,
    paddingHorizontal: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.88)',
    shadowColor: '#4C1D95',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 8,
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  menuIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.55)',
    borderWidth: 1.2,
    borderColor: 'rgba(255, 255, 255, 0.85)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4C1D95',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
  },
  dotsIconVertical: {
    height: 16,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  miniMenuDot: {
    width: 3.5,
    height: 3.5,
    borderRadius: 2,
    backgroundColor: '#6D28D9',
  },
  locationTitleBox: {
    alignItems: 'center',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  locationPinIcon: {
    fontSize: 14,
  },
  locationName: {
    fontSize: 17,
    fontWeight: '800',
    color: '#2E1065',
    letterSpacing: -0.2,
  },
  dateTimeText: {
    fontSize: 11.5,
    color: '#6B7280',
    fontWeight: '600',
    marginTop: 2,
  },
  plusIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.55)',
    borderWidth: 1.2,
    borderColor: 'rgba(255, 255, 255, 0.85)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4C1D95',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
  },
  plusText: {
    fontSize: 22,
    fontWeight: '700',
    color: '#6D28D9',
    lineHeight: 24,
  },
  heroWeatherRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 8,
    paddingHorizontal: 6,
  },
  tempLeftCol: {
    flex: 1,
  },
  heroTempNumber: {
    fontSize: 66,
    fontWeight: '900',
    color: '#4C1D95',
    letterSpacing: -2,
    lineHeight: 72,
  },
  heroConditionText: {
    fontSize: 19,
    fontWeight: '700',
    color: '#6D28D9',
    marginTop: 2,
  },
  heroArtRightCol: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricsStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: 'rgba(255, 255, 255, 0.65)',
    borderRadius: 22,
    paddingVertical: 14,
    paddingHorizontal: 10,
    marginVertical: 14,
    borderWidth: 1.2,
    borderColor: 'rgba(255, 255, 255, 0.88)',
    shadowColor: '#4C1D95',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
  },
  metricItem: {
    alignItems: 'center',
    flex: 1,
  },
  metricIcon: {
    fontSize: 16,
    marginBottom: 4,
  },
  metricValue: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#2E1065',
  },
  metricLabel: {
    fontSize: 10.5,
    color: '#6B7280',
    fontWeight: '600',
    marginTop: 2,
  },
  bottomSpacer: {
    height: 40,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(46, 16, 101, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 30,
    padding: 24,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.98)',
    shadowColor: '#4C1D95',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.25,
    shadowRadius: 28,
    elevation: 12,
  },
  modalTitle: {
    fontSize: 19,
    fontWeight: '800',
    color: '#2E1065',
    marginBottom: 4,
  },
  modalSub: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 16,
  },
  modalLocItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 18,
    marginBottom: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderWidth: 1.2,
    borderColor: '#EDE9FE',
  },
  modalLocItemActive: {
    backgroundColor: '#F3E8FF',
    borderColor: '#C084FC',
  },
  modalLocLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  modalLocPin: {
    fontSize: 16,
  },
  modalLocName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1F2937',
  },
  modalLocRegion: {
    fontSize: 11,
    color: '#6B7280',
  },
  modalLocTemp: {
    fontSize: 15,
    fontWeight: '800',
    color: '#6D28D9',
  },
})
