import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  container: {
    width: 140,
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  sunOrb: {
    position: 'absolute',
    top: 6,
    right: 22,
    width: 52,
    height: 52,
    zIndex: 1,
  },
  sunSolo: {
    position: 'relative',
    top: 0,
    right: 0,
    width: 70,
    height: 70,
  },
  sunGlow: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#FDE047',
    opacity: 0.65,
    shadowColor: '#EAB308',
    shadowOpacity: 0.8,
    shadowRadius: 18,
  },
  sunCore: {
    position: 'absolute',
    width: '90%',
    height: '90%',
    top: '5%',
    left: '5%',
    borderRadius: 999,
    backgroundColor: '#FACC15',
    borderWidth: 2,
    borderColor: '#FEF08A',
  },
  sunRay: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FACC15',
  },
  moonOrb: {
    width: 65,
    height: 65,
    borderRadius: 999,
    position: 'relative',
  },
  moonCore: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderLeftWidth: 14,
    borderBottomWidth: 14,
    borderColor: '#C084FC',
    transform: [{ rotate: '-35deg' }],
  },
  starBead1: {
    position: 'absolute',
    top: 8,
    right: 12,
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#FDE047',
  },
  starBead2: {
    position: 'absolute',
    top: 24,
    right: 4,
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#FDE047',
  },
  cloudGroup: {
    width: 106,
    height: 68,
    position: 'relative',
    zIndex: 2,
    marginTop: 18,
  },
  cloudBackDrop: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    shadowColor: '#4C1D95',
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  cloudPuffLarge: {
    position: 'absolute',
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    top: -12,
    left: 20,
    shadowColor: '#6D28D9',
    shadowOpacity: 0.08,
    shadowRadius: 6,
  },
  cloudPuffSmall: {
    position: 'absolute',
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    top: 2,
    right: 8,
  },
  cloudBase: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 38,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.9)',
  },
  rainGroup: {
    position: 'absolute',
    bottom: -18,
    left: 12,
    width: 90,
    height: 24,
    zIndex: 3,
  },
  rainDrop: {
    position: 'absolute',
    width: 6,
    height: 14,
    borderRadius: 3,
    backgroundColor: '#60A5FA',
    transform: [{ rotate: '15deg' }],
    opacity: 0.85,
  },
  lightningBolt: {
    position: 'absolute',
    bottom: -16,
    left: 42,
    zIndex: 4,
  },
  lightningText: {
    fontSize: 22,
  },
  windWaveGroup: {
    position: 'absolute',
    bottom: -12,
    left: 14,
    width: 80,
    gap: 4,
  },
  windWaveLine1: {
    width: 65,
    height: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(196, 181, 253, 0.9)',
  },
  windWaveLine2: {
    width: 45,
    height: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(196, 181, 253, 0.7)',
    marginLeft: 15,
  },
  snowGroup: {
    position: 'absolute',
    bottom: -14,
    left: 12,
    width: 90,
    height: 20,
  },
  snowFlake: {
    position: 'absolute',
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#E0E7FF',
  },
})

