import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#8B5CF6',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 90,
    alignItems: 'center',
  },
  mainCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 32,
    padding: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.88)',
    shadowColor: '#4C1D95',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 8,
  },
  profileHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  avatarCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: '#6D28D9',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    borderWidth: 3.5,
    borderColor: '#DDD6FE',
    shadowColor: '#6D28D9',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
  avatarLetter: {
    fontSize: 30,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  profileName: {
    fontSize: 21,
    fontWeight: '800',
    color: '#2E1065',
    letterSpacing: -0.2,
  },
  profileEmail: {
    fontSize: 12.5,
    color: '#6B7280',
    marginTop: 2,
    fontWeight: '500',
  },
  settingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.78)',
    borderRadius: 22,
    padding: 14,
    borderWidth: 1.2,
    borderColor: 'rgba(255, 255, 255, 0.9)',
    marginBottom: 20,
    shadowColor: '#4C1D95',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
  },
  settingTextCol: {
    flex: 1,
  },
  settingTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#2E1065',
  },
  settingSub: {
    fontSize: 11,
    color: '#6B7280',
    marginTop: 2,
  },
  unitTogglePill: {
    flexDirection: 'row',
    backgroundColor: 'rgba(237, 233, 254, 0.85)',
    borderRadius: 18,
    padding: 4,
    borderWidth: 1,
    borderColor: '#DDD6FE',
  },
  unitHalf: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 14,
  },
  unitHalfActive: {
    backgroundColor: '#6D28D9',
    shadowColor: '#5B21B6',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  unitText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#6D28D9',
  },
  unitTextActive: {
    color: '#FFFFFF',
  },
  activitiesHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#2E1065',
  },
  sectionCount: {
    fontSize: 12,
    fontWeight: '800',
    color: '#6D28D9',
  },
  sectionSub: {
    fontSize: 11.5,
    color: '#6B7280',
    marginBottom: 12,
    lineHeight: 16,
  },
  activitiesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 24,
  },
  activityTogglePill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 13,
    borderRadius: 18,
    borderWidth: 1.5,
    gap: 6,
  },
  pillSelected: {
    backgroundColor: '#6D28D9',
    borderColor: '#A78BFA',
    shadowColor: '#5B21B6',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
  },
  pillUnselected: {
    backgroundColor: 'rgba(255, 255, 255, 0.65)',
    borderColor: 'rgba(255, 255, 255, 0.85)',
  },
  actIcon: {
    fontSize: 14,
  },
  actName: {
    fontSize: 12,
    fontWeight: '700',
  },
  actNameSelected: {
    color: '#FFFFFF',
  },
  actNameUnselected: {
    color: '#374151',
  },
  pillCheck: {
    fontSize: 11,
    fontWeight: '900',
    color: '#FDE047',
    marginLeft: 2,
  },
  actionsList: {
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(109, 40, 217, 0.1)',
    paddingTop: 16,
  },
  actionBtnSecondary: {
    backgroundColor: 'rgba(255, 255, 255, 0.82)',
    borderRadius: 20,
    paddingVertical: 13,
    alignItems: 'center',
    borderWidth: 1.2,
    borderColor: 'rgba(255, 255, 255, 0.95)',
    shadowColor: '#4C1D95',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
  },
  actionSecondaryText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#6D28D9',
  },
  signOutBtn: {
    backgroundColor: 'rgba(254, 226, 226, 0.85)',
    borderRadius: 20,
    paddingVertical: 13,
    alignItems: 'center',
    borderWidth: 1.2,
    borderColor: '#FECACA',
  },
  signOutText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#DC2626',
  },
  bottomSpacer: {
    height: 40,
  },
})
